apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-shell
  namespace: default

spec:
  selector:
    matchLabels:
      app: wisecow

  process:
    matchPaths:
      - path: /bin/bash
      - path: /bin/sh

  action: Block